### ISSUE TITLE
script validation step isn't actually replacing a known broken/missing file

### ISSUE THREAD

**Issue by Zistack** [t3nk3y/palia_steam_helper#4]
So I'm just trying to set up the game.  I follow the instructions, and things mostly go well.  The only hitch at first is that the little window that pops up for downloading the game actually stopped at about 7% the first time around for no apparent reason.  I hit OK and relaunched the script.  It seemed to pick up where it left off and things appeared to be fine at that point.

Well, the game doesn't actually _launch_ once I get to that part.  OK, well, I am software dev, and I know things about getting games to work in proton, so I go digging.  The log says that the file `pakchunk0-WindowsClient.pak` failed to mount "invalid file".  I figure it was corrupted by the hiccup in the installation process.  I delete it, not yet having read the gory details at the bottom of the README that say this issue should generally be fixed automatically by the script anyways.  I was assuming that the file being missing would cause the script to re-download it (which should also work).  For some reason, none of this works.  I also tried deleting the known hashes file, also in attempt to get the game to re-validate.

As far as getting the script to go through the re-validation process goes, it seems like anything you would expect to work actually does work, but then the file never actually gets replaced.  What gives?  My own cursory look at the relevant parts of the python script didn't reveal any obvious issues that might cause this behavior.

I've gone and attached the most recent log file just in case you can glean anything more from it than I can.  I note that the lines about validation don't mention the offending file at all, even though I verified that it is listed in both `known-hashes.json` and `base-hashes.json`.

[palia_steam_helper.log](https://github.com/t3nk3y/palia_steam_helper/files/12639803/palia_steam_helper.log)

**Comment by t3nk3y** [comment]
Wow, what timing.  Sorry you ran in to this problem.  We just so happened
to have noticed this exact issue earlier on Friday.  And pushed a fix for
it, like, minutes before you posted your issue.  Also forgot to mention it
in the git change log.

The parts of the script that check the base files(which that pak is one of,
the largest and most likely to get broken during download) was failing to
do it's job because we forgot to update that but to make sure the base hash
file was loaded before checking.  That caused it to not scan for any base
files.

You made a lot of correct assumptions on your troubleshooting, sorry for
the slip up on our end.

If you pull an update, it should fix the issue for you.

This latest version will also let you know when the game crashes with a
problem, show you relevant error lines, and for a recheck of files on the
next launch, so it should be much more robust.

Please let us know if this fixes the problem for you.

Thanks for the bug report, and your detailed investigation.
-Madalee

**Comment by Zistack** [comment]
The launcher works beautifully now.  Apparently I had several corrupt files, and it actually took a couple of tries to get that first one to download all the way without breaking.  I suspect that this has more to do with the file servers than this script, though.

Consider adding the ability for the script to check for updates to itself next.  A manual update for a fix like this is no problem for me, but would be beyond most ordinary users, and would be a little extra awkward on the steam deck simply due to limited peripherals.

Ima mark this as closed, since the script now appears to work as intended, and my game launches.  Thanks for the swift reply.
